services:
  - type: web
    name: nuxo-bot
    env: python
    rootDir: bot_whatsapp
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1 --proxy-headers
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 8000 